### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by AmyScript** [wessberg/scroll-behavior-polyfill#1] opened 2018-07-16 21:30 UTC
This doesn't seem to provide a polyfill for Safari when using:
scroll-behavior: smooth 
on a non-root element.

**Comment by wessberg** [comment] 2018-07-17 08:59
Hi!
Noted. I'll look into it. When you say root, do you mean local to the document root, or local to a Shadow Root? Or in other words, are you using Shadow DOM? I'm using the polyfill in production for a site where I can confirm Safari is working under at least some circumstances. But please know that I'm strongly considering changing this polyfill to not parse stylesheets for `scroll-behavior: smooth` since it has quite negative impacts on performance on mobile from my own testing

**Comment by whaaaley** [comment] 2019-01-08 01:37
I just installed your polyfill. It works great! I can't reproduce this in safari on my end. I would also encourage not parsing stylesheets, however, is it possible to get a CSS polyfill working with CSSOM?

**Comment by wessberg** [comment] 2019-01-08 15:17
Unfortunately, The CSSOM discards properties that it doesn't understand, and there are no ways to access the raw key-value pairs of, say, a block of CSS declarations. This is the reason why CSS polyfills require manual parsing of stylesheets to come up with a virtual representation of the CSSOM.

Here's a codepen that illustrates this behavior: https://codepen.io/anon/pen/aPKxXW

@AmyScript, I'm gonna go ahead and close this issue under the assumption that the issue have been resolved :-)

**Closed as completed by wessberg** 2019-01-08 15:17 UTC
